from easydict import EasyDict as edict

__APP_SETTINGS__ = edict()

__APP_SETTINGS__.RUN_ROOM_M1 = True
__APP_SETTINGS__.RUN_ROOM_M2 = True


__APP_SETTINGS__.EXTRACT_FRAMES_ROOM_M1 = True
__APP_SETTINGS__.EXTRACT_FRAMES_ROOM_M2 = True


__APP_SETTINGS__.ROOM_M1_OCCU_THRESH = 5
__APP_SETTINGS__.ROOM_M2_OCCU_THRESH = 5


__APP_SETTINGS__.STARTTIME_CLEAN_ACT = ''